baseURL = "https://something"
googleAnalytics = "UA-xxxxx-7"

[params]
brand = "SOME BRAND"
navOne = "How to do things"
navTwo = "Why to do things"
navButton = "Button"
copyright = "Copyright"
terms = "Terms & Conditions"
privacy = "Privacy Policy"
